# Generated by Django 4.2.1 on 2023-05-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
