# Generated by Django 4.2.1 on 2023-05-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0003_remove_image_file_name_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
