# Generated by Django 4.2.1 on 2023-05-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0004_image_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
