# Generated by Django 4.2.1 on 2023-05-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0005_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
