# Generated by Django 4.2.1 on 2023-07-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0007_alter_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=240)),
                ('password', models.CharField(max_length=20)),
                ('regist_date', models.DateTimeField(verbose_name='date registed')),
            ],
        ),
    ]
