# Generated by Django 4.2.1 on 2023-08-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0010_alter_account_date_joined_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
