# Generated by Django 4.2.1 on 2023-09-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0012_alter_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
