# Generated by Django 4.2.1 on 2023-09-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0013_product_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
