# Generated by Django 4.2.1 on 2023-09-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0014_alter_product_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
    ]
