# Generated by Django 4.2.1 on 2023-12-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0016_artist_product_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
