# Generated by Django 4.2.1 on 2023-12-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0018_alter_artist_artist_id_alter_artist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
