# Generated by Django 4.2.1 on 2023-12-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0019_artist_profile_picture_alter_artist_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='regist_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='LINK',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regist_date', models.DateField(null=True)),
                ('artist', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ec.artist')),
            ],
        ),
    ]
