# Generated by Django 4.2.1 on 2023-12-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0020_artist_profile_picture_artist_regist_date_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='site',
            field=models.CharField(choices=[], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
